### PR TITLE
Reset cached negative item after reflesh

### PR DESCRIPTION
**Pull request by qiwzhang**
Signed-off-by: Wayne Zhang <qiwzhang@google.com>

The issue:
when an negative response is cached, its result are used for next refresh interval,  this is by design.  
But even after many refresh intervals,  the negative response are still used.  refresh interval is 1 second.
This result in that  after a 429,   a request after a couple minutes later is still rejected.   

The fix: after refresh,  set the cache item to an empty response which is a positive response.
refresh could happen at two places: 
1) when cache item is deleted due to age,  age is set to refresh_interval.
2) when a new request comes, cached item passes the refresh time.

This is to fix b/194667510

### CODE REVIEW

**Comment by nareddyt** [comment]
Maybe I am misunderstanding this change - Are you sure this will not break a normal production use case?

This change will allow at least 1 request through every 1 second regardless of the SuperQuota response, because it manually sets a positive response on refresh. We do not want this behavior. If SuperQuota is returning RESOURCE_EXHUASTED consistently, we should not be allowing requests through every second on refresh.

The correct approach should be to modify the refresh algorithm to refresh all the time, not only when a new request comes in.

**Comment by qiwzhang** [comment]
Thanks,  you got a good point.  This change will not work for small limits,  e.g. < 60 per minute, since it allows 1 request per second.  Thanks for catching this.

**Comment by qiwzhang** [comment]
As your proposed approach of refresh all the time,  we could not do that.   As current QuotaAllocate API only allows the client to allocate,  not poking available.   We have to allocate something in order to check if it is available.   We could not keep "allocating" in the background without any incoming requests.

**Comment by qiwzhang** [comment]
We may have to rely on cache expiration to reset the cached negative response. Current expiration duration is [10m](https://github.com/cloudendpoints/service-control-client-cxx/blob/master/include/aggregation_options.h#L35).  
We can reduce to 1m,  Since the rate limiting window is per minute,  it makes more sense to expire all cache items in 1 minute.

What do you think?

**Comment by nareddyt** [comment]
> As current QuotaAllocate API only allows the client to allocate, not poking available. We have to allocate something in order to check if it is available. We could not keep "allocating" in the background without any incoming requests.

Technically it is supported: https://github.com/googleapis/googleapis/blob/26871a2f833a52e0b71105adeea4796a8828ebe2/google/api/servicecontrol/v1/quota_controller.proto#L107

Not sure how much change to the client this will need.

> We may have to rely on cache expiration to reset the cached negative response. Current expiration duration is 10m.
We can reduce to 1m, Since the rate limiting window is per minute, it makes more sense to expire all cache items in 1 minute.

Your idea makes sense, but I do not know the implications of reducing the expiration time. Do you know the context for this comment? https://github.com/cloudendpoints/service-control-client-cxx/blob/facba8b00c5c2281a538f0e929d6df1a5b596d06/include/aggregation_options.h#L42

**Comment by qiwzhang** [comment]
Thanks @nareddyt  I think I will do followings
1) reduce default expiration time from 10m to 1m.   It is still 10 time larger than default refresh time of 1s.

2) It is good to know, QuotaAllocate API supports "Check_Only".   We can use it to check all negative cached items periodically, Once the quota is available, and reset the cached result from negative to positive.  This is just an enhancement, to grant the request earlier than the first request after 429.  Otherwise the first request after 429 is always 429.

**Comment by qiwzhang** [comment]
https://github.com/cloudendpoints/service-control-client-cxx/pull/42

**Pull request closed without merging**
